const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// 0126: the tuner must run the SAME ffmpeg arguments as today's sessions - every
// capture-verified decision (igndts per feed, -dts_delta_threshold 60, hvc1,
// aac_adtstoasc, HE-AAC, pacing) lives in them. buildFFmpegArgs was split into
// buildSourceArgs + buildHlsOutputArgs for that; this proves the split changed
// nothing, token for token, against arguments generated by the 0125 code
// (test/fixtures/ffmpeg-args-golden.json, from test/fixtures/ffmpeg-args-matrix.js),
// and that a tuner differs only in how the HLS muxer keeps its window.
const { TranscodeSession } = require('../server/services/transcodeSession');
const { TunerSession } = require('../server/services/tuner');
const { URL_, matrix, SESSION_DIR } = require('./fixtures/ffmpeg-args-matrix');
const golden = require('./fixtures/ffmpeg-args-golden.json');

function quietly(fn) {
    const log = console.log;
    console.log = () => {};
    try { return fn(); } finally { console.log = log; }
}

test('the golden fixture covers the whole option matrix', () => {
    assert.deepEqual(golden.map(g => g.options), matrix());
    assert.ok(golden.length > 100);
});

test('buildFFmpegArgs produces exactly the 0125 arguments for every option set', () => {
    for (const { options, args } of golden) {
        const s = new TranscodeSession(URL_, options);
        s.dir = SESSION_DIR;
        s.playlistPath = path.join(SESSION_DIR, 'stream.m3u8');
        assert.deepEqual(quietly(() => s.buildFFmpegArgs()), args, JSON.stringify(options));
    }
});

test('a tuner runs the same source/codec arguments; only the HLS window differs', () => {
    for (const { options, args } of golden) {
        const t = new TunerSession(URL_, options);
        t.dir = SESSION_DIR;
        t.playlistPath = path.join(SESSION_DIR, 'ffmpeg.m3u8');
        const tunerArgs = quietly(() => t.buildTunerArgs());
        const cut = args.indexOf('-f');
        assert.equal(args[cut + 1], 'hls');
        assert.deepEqual(tunerArgs.slice(0, cut), args.slice(0, cut), 'input, timestamps, copy/encode and audio are identical');
        const out = tunerArgs.slice(cut);
        assert.deepEqual(out.slice(0, 4), ['-f', 'hls', '-hls_time', '4']);
        assert.equal(out[out.indexOf('-hls_flags') + 1], 'independent_segments+temp_file', 'the server deletes segments, not ffmpeg');
        assert.ok(!out.includes('-hls_delete_threshold'));
        // Segment type, init name and file pattern: as the session's.
        const tail = (a) => a.slice(a.indexOf('-hls_segment_type'), -1);
        assert.deepEqual(tail(out), tail(args));
        assert.equal(out[out.length - 1], path.join(SESSION_DIR, 'ffmpeg.m3u8'));
    }
});

test('the tuner key is the arguments: equal options share a key, any argument change does not', () => {
    const base = golden[0].options;
    const key = (o) => quietly(() => { const t = new TunerSession(URL_, o); return t.computeKey(); });
    assert.equal(key(base), key({ ...base }), 'two tuners with the same options (and different directories) share a key');
    assert.notEqual(key(base), key({ ...base, segmentType: 'mpegts' }));
    assert.notEqual(key(base), key({ ...base, dtsUneven: true }));
    assert.notEqual(key(base), key({ ...base, audioMode: 'encode' }));
    assert.notEqual(key(base), key({ ...base, userAgent: 'Other/2' }));
    assert.notEqual(key(base), key({ ...base, videoRange: 'SDR', fps: '25/1' }), 'the master playlist is part of it');
    assert.notEqual(quietly(() => new TunerSession('http://provider.invalid/other.ts', base).computeKey()), key(base));
    // Options that change nothing in the arguments do not split viewers.
    assert.equal(key(base), key({ ...base, owner: 'device:a', live: true }));
});
