services:
  pigtv:
    image: ghcr.io/maroge1990/pigtv:latest
    build: https://github.com/maroge1990/PigTV.git#main
    container_name: pigtv
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      # DVR recordings - point this at wherever you want recorded shows stored
      - ./recordings:/app/recordings
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000 # Internal container port
